name: integration

on:
  pull_request:
    branches:
      - development
      - staging
      - main

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Lint Test
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --diff --dry-run

  test:
    runs-on: ubuntu-latest
    services:
        postgres:
          image: postgres:13
          env:
            POSTGRES_USER: carbonaut
            POSTGRES_PASSWORD: carbonaut
            POSTGRES_DB: carbonaut_testing
          ports:
          - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Setup Configuration Environment File
        run: |
          cp .env.example.test .env.test
          sed -i 's/^DB_HOST=database$/DB_HOST=localhost/' .env.test

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Run Integration Tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: vendor/bin/phpunit

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --prefer-dist

      - name: Run Static Analysis
        run: vendor/bin/phpstan analyse
